### ISSUE TITLE
SAXParseException; lineNumber: 8; columnNumber: 35; cvc-complex-type.2.4.a: Foi detectado um conteúdo inválido começando com o elemento 'exclude-unlisted-classes'

### ISSUE THREAD

**Issue by gilbertoca** [arthurgregorio/web-budget#148]
Esperimentando a [versão v2.1.2](https://github.com/arthurgregorio/web-budget/releases/tag/v2.1.2) com o [Payara Micro ](http://www.payara.fish/introducing_payara_micro):

```bash
java -jar ~/Downloads/Ambiente_java/payara-micro-4.1.1.154.jar --deploy webBudget-2.1.2.war 
.
.
.
```

```bash
[2015-12-30T12:14:57.446-0200] [Payara 4.1] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1451484897446] [levelValue: 1000] [[
  Exception during lifecycle processing
java.io.IOException: org.xml.sax.SAXParseException; lineNumber: 8; columnNumber: 35; Deployment descriptor file META-INF/persistence.xml in archive [classes].  cvc-complex-type.2.4.a: Foi detectado um conteúdo inválido começando com o elemento 'exclude-unlisted-classes'. Era esperado um dos '{"http://xmlns.jcp.org/xml/ns/persistence":validation-mode, "http://xmlns.jcp.org/xml/ns/persistence":properties}'.
	at org.glassfish.javaee.core.deployment.DolProvider.processDOL(DolProvider.java:196)
	at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:227)
	at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:96)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.loadDeployer(ApplicationLifecycle.java:881)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainerInfos(ApplicationLifecycle.java:821)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:378)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
	at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.deploy(DeployerImpl.java:134)
	at fish.payara.micro.PayaraMicro.deployAll(PayaraMicro.java:924)
	at fish.payara.micro.PayaraMicro.bootStrap(PayaraMicro.java:711)
	at fish.payara.micro.PayaraMicro.main(PayaraMicro.java:105)
Caused by: org.xml.sax.SAXParseException; lineNumber: 8; columnNumber: 35; Deployment descriptor file META-INF/persistence.xml in archive [classes].  cvc-complex-type.2.4.a: Foi detectado um conteúdo inválido começando com o elemento 'exclude-unlisted-classes'. Era esperado um dos '{"http://xmlns.jcp.org/xml/ns/persistence":validation-mode, "http://xmlns.jcp.org/xml/ns/persistence":properties}'.
	at com.sun.enterprise.deployment.io.DeploymentDescriptorFile.read(DeploymentDescriptorFile.java:328)
	at com.sun.enterprise.deployment.archivist.ExtensionsArchivist.open(ExtensionsArchivist.java:179)
	at com.sun.enterprise.deployment.archivist.PersistenceArchivist.readPersistenceDeploymentDescriptor(PersistenceArchivist.java:144)
	at com.sun.enterprise.deployment.archivist.WarPersistenceArchivist.open(WarPersistenceArchivist.java:93)
	at com.sun.enterprise.deployment.archivist.Archivist.readRestDeploymentDescriptors(Archivist.java:405)
	at com.sun.enterprise.deployment.archivist.Archivist.openWith(Archivist.java:292)
	at com.sun.enterprise.deployment.archivist.ApplicationFactory.openWith(ApplicationFactory.java:232)
	at org.glassfish.javaee.core.deployment.DolProvider.processDOL(DolProvider.java:193)
	... 25 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 8; columnNumber: 35; cvc-complex-type.2.4.a: Foi detectado um conteúdo inválido começando com o elemento 'exclude-unlisted-classes'. Era esperado um dos '{"http://xmlns.jcp.org/xml/ns/persistence":validation-mode, "http://xmlns.jcp.org/xml/ns/persistence":properties}'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:452)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3230)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1790)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:740)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2787)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at com.sun.enterprise.deployment.io.DeploymentDescriptorFile.read(DeploymentDescriptorFile.java:318)
	... 32 more
]]

```

**Comment by arthurgregorio** [comment]
Este erro é causado pela validação do XSD do persistence.xml.

Caso a versão que esteja usando seja inferior a 2.1 pode ocorrer este tipo de comportamento.. No Glassfish 4 e no Wildfly 9 (ambos proveem a versão 2.x com Hibernate 4) o problema não ocorre..

Poderia me informar qual a versão que esta usando? Ou algum outro detalhe a mais sobre o ambiente de execução?

**Comment by gilbertoca** [comment]
Oi, @arthurgregorio.  Está no post como link: [payara-micro-4.1.1.154](http://www.payara.fish/downloads). Editei para ficar mais evidente.

**Comment by arthurgregorio** [comment]
Como este app server não é de uso muito comum, classificado como **help wanted** caso alguém da comunidade queira dar uma contribuição com uma possível correção para o problema.

Caso contrário, será feito quando em algum momento o projeto possa ser colocado entre as atividades prioritárias do sistema.

**Comment by arthurgregorio** [comment]
Verificar homologação para a ultima versão disponível do webserver. 

Testar no linux e windows

**Comment by arthurgregorio** [comment]
O problema era relacionado ao datasource, como o sistema requer um, para utilização com o payara micro é necessário definir um manualmente conforme exemplo: 

https://github.com/payara/Payara-Examples/tree/master/Payara-Micro/datasource-example

Como não se trata de um solução amplamente utilizada fica a cargo do usuário/desenvolvedor configurar o sistema para tal, alterando o web.xml e provendo as libs.
